(() => {
  'use strict';
  const BUILD='Build026.2.1';
  const PORTAL_BASE='https://g-link-portal.pages.dev';
  const OFFLINE_GRACE_MS=72*60*60*1000;
  const LOCAL_KEY='gLink_standardAuthRemembered';
  const SESSION_KEY='gLink_standardAuthSession';
  let gate=null,statusBar=null,currentState=null;

  function diag(event,details={}){const entry={time:new Date().toISOString(),build:BUILD,event,details};try{console.info('[G-Link Auth]',entry);sessionStorage.setItem('gLink_authDiagnostics',JSON.stringify(entry));}catch(e){}}
  function readState(){for(const store of [sessionStorage,localStorage]){try{const raw=store.getItem(store===localStorage?LOCAL_KEY:SESSION_KEY);if(raw)return {...JSON.parse(raw),storage:store===localStorage?'local':'session'};}catch(e){}}return null;}
  function saveState(state,remember){clearState();const payload=JSON.stringify({...state,remember:Boolean(remember)});(remember?localStorage:sessionStorage).setItem(remember?LOCAL_KEY:SESSION_KEY,payload);currentState={...state,remember:Boolean(remember),storage:remember?'local':'session'};}
  function clearState(){try{localStorage.removeItem(LOCAL_KEY);}catch(e){}try{sessionStorage.removeItem(SESSION_KEY);}catch(e){}currentState=null;}
  function api(path,options={}){return fetch(`${PORTAL_BASE}${path}`,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})},cache:'no-store'});}
  async function parseResponse(response){let data={};try{data=await response.json();}catch(e){data={message:`PortalからJSON以外の応答を受信しました。HTTP ${response.status}`};}if(!response.ok){const err=new Error(data.message||`HTTP ${response.status}`);err.status=response.status;err.data=data;throw err;}return data;}
  function appRoot(){return document.body||document.documentElement;}
  function hideApp(){appRoot()?.classList.add('glink-auth-hidden-app');}
  function showApp(){appRoot()?.classList.remove('glink-auth-hidden-app');if(gate)gate.hidden=true;}
  function createGate(){if(gate)return gate;gate=document.createElement('section');gate.id='glinkAuthGate';gate.innerHTML=`<div class="glink-auth-card"><div class="glink-auth-logo">G</div><p class="glink-auth-kicker">G-LINK STANDARD</p><h1 class="glink-auth-title">ライセンス認証</h1><p class="glink-auth-lead">管理者から発行されたライセンスIDと初期パスワードを入力してください。</p><form id="glinkAuthForm"><div class="glink-auth-field"><label for="glinkLicenseId">ライセンスID</label><input id="glinkLicenseId" autocomplete="username" placeholder="GL-000001" required></div><div class="glink-auth-field"><label for="glinkLicensePassword">パスワード</label><input id="glinkLicensePassword" type="password" autocomplete="current-password" required></div><label class="glink-auth-remember"><input id="glinkRemember" type="checkbox"><span>この端末でログイン状態を保持する<br><small>共用端末ではチェックを外してください。</small></span></label><button id="glinkAuthSubmit" class="glink-auth-button" type="submit">認証して起動</button><p id="glinkAuthMessage" class="glink-auth-message" aria-live="polite"></p></form><p class="glink-auth-note">通信障害時は、最後の正常認証から72時間以内に限りオフライン起動できます。Command機能はオフライン中は利用できません。</p></div>`;document.documentElement.appendChild(gate);gate.querySelector('#glinkAuthForm').addEventListener('submit',login);return gate;}
  function message(text,success=false){createGate();const el=gate.querySelector('#glinkAuthMessage');el.textContent=text||'';el.classList.toggle('success',success);}
  function showLogin(text=''){hideApp();createGate().hidden=false;message(text);setTimeout(()=>gate.querySelector('#glinkLicenseId')?.focus(),0);}
  function showStatus(state,offline=false){if(statusBar)statusBar.remove();statusBar=document.createElement('div');statusBar.className=`glink-auth-status${offline?' offline':''}`;const org=state.organization||{};statusBar.innerHTML=`<span>${offline?'オフライン認証':'認証済み'}：${escapeHtml(org.name||'利用機関')}（${escapeHtml(org.licenseId||'')}）${offline?'・残り'+offlineRemaining(state):''}</span><button type="button">ログアウト</button>`;statusBar.querySelector('button').addEventListener('click',logout);document.documentElement.appendChild(statusBar);}
  function escapeHtml(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function offlineRemaining(state){const left=Math.max(0,OFFLINE_GRACE_MS-(Date.now()-Date.parse(state.lastValidatedAt||0)));const h=Math.floor(left/3600000);const m=Math.floor((left%3600000)/60000);return `${h}時間${m}分`;}
  function canOffline(state){const t=Date.parse(state?.lastValidatedAt||'');return Boolean(state?.token&&Number.isFinite(t)&&Date.now()-t<=OFFLINE_GRACE_MS&&state?.organization?.standard);}
  function activate(state,offline=false){currentState=state;showApp();showStatus(state,offline);window.GLinkLicense={authenticated:true,offline,organization:state.organization,commandEnabled:Boolean(state.organization?.command&&!offline),portalBase:PORTAL_BASE,build:BUILD};diag(offline?'offline grace activated':'online authentication valid',{licenseId:state.organization?.licenseId});window.dispatchEvent(new CustomEvent('glink-license-ready',{detail:window.GLinkLicense}));}
  async function validate(state){try{const response=await api('/api/app/auth/validate',{method:'GET',headers:{Authorization:`Bearer ${state.token}`}});const data=await parseResponse(response);const next={...state,organization:data.organization,expiresAt:data.sessionExpiresAt,lastValidatedAt:new Date().toISOString()};saveState(next,state.remember);activate(next,false);}catch(error){diag('validation failed',{status:error.status||0,message:error.message});if(error.status){clearState();showLogin(error.message||'再ログインしてください。');return;}if(canOffline(state)){activate(state,true);return;}showLogin('Portalへ接続できず、72時間のオフライン猶予も終了しています。通信環境を確認してください。');}}
  async function login(event){event.preventDefault();const button=gate.querySelector('#glinkAuthSubmit');button.disabled=true;message('Portalへ認証しています…',true);try{const licenseId=gate.querySelector('#glinkLicenseId').value.trim().toUpperCase();const password=gate.querySelector('#glinkLicensePassword').value;const remember=gate.querySelector('#glinkRemember').checked;const response=await api('/api/app/auth/login',{method:'POST',body:JSON.stringify({licenseId,password,remember})});const data=await parseResponse(response);const state={token:data.token,expiresAt:data.expiresAt,lastValidatedAt:new Date().toISOString(),organization:data.organization,remember};saveState(state,remember);activate(state,false);}catch(error){if(error.data?.passwordChangeUrl){message('初回ログインのため、各機関専用のパスワードを設定してください。利用機関ログインページを開きます。');window.open(error.data.passwordChangeUrl,'_blank','noopener');}else message(`${error.message}${error.data?.diagnosticCode?'（'+error.data.diagnosticCode+'）':''}`);}finally{button.disabled=false;}}
  async function logout(){const state=currentState||readState();clearState();try{if(state?.token)await api('/api/app/auth/logout',{method:'POST',headers:{Authorization:`Bearer ${state.token}`}});}catch(e){}location.reload();}
  async function boot(){hideApp();createGate();const state=readState();if(!state){showLogin();return;}await validate(state);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
